added integer check

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -20,6 +20,14 @@ jobs:
               echo "Empty Response"
               exit 1
           fi
+          if [ "$REMOTEAPPVER" -eq "$REMOTEAPPVER" ] 2>/dev/null
+          then
+              echo "REMOTEAPPVER is an integer"
+              exit 0
+          else
+              echo "ERROR: parameter must be an integer"
+              exit 1
+          fi
           if [[ "$LOCALAPPVER" != "$REMOTEAPPVER" ]]; then
               echo "$REMOTEAPPVER" >sandstorm.version
               exit 0
